---
title: "on z scores"
author: "Xinyu Zhang"
date: "7/2/2020"
output: html_document
---
Reshaping the data:
```{r}
library(dplyr)
#reading in listening test results
listener1 <- read.csv("Results_AK.csv", header = TRUE, sep = ";")
listener2 <- read.csv("Results_KS.csv", header = TRUE, sep = ";")
#renaming the two answers, removing column "Num"
SLP1 <- listener1 %>%
  dplyr::select(-Num) %>% 
  rename(Roughness = Answer1, Breathiness = Answer2)
SLP1$dummy <- paste(SLP1$Speaker, "-", SLP1$T)
#nrow(SLP1) #96

SLP2 <- listener2 %>%
  rename(Roughness = Answer1, Breathiness = Answer2)%>%
  dplyr::select(-Num)
SLP2$dummy <- paste(SLP2$Speaker, "-", SLP2$T)
#nrow(SLP2) #96

AVQI <- read.csv("AVQI_results_new.csv")
AVQI$dummy <- paste(AVQI$Speaker, "-", AVQI$T)
AVQI$Jitter <- as.numeric(levels(AVQI$Jitter))[AVQI$Jitter]
```

```{r}
library(dplyr)
mB1 <- mean(SLP1$Breathiness)#AK
sdB1 <- sd(SLP1$Breathiness)#AK
mB2 <- mean(SLP2$Breathiness)#KS
sdB2 <- sd(SLP2$Breathiness)#KS
mR1 <- mean(SLP1$Roughness)#AK
sdR1 <- sd(SLP1$Roughness)#AK
mR2 <- mean(SLP2$Roughness)#KS
sdR2 <- sd(SLP2$Roughness)#KS
zSLP1 <- SLP1 %>% 
  mutate(zBreathy = (Breathiness-mB1)/sdB1, zRough = (Roughness-mR1)/sdR1) %>% 
  dplyr::select(-A, -Z, -T)
zSLP2 <- SLP2 %>% 
  mutate(zBreathy = (Breathiness-mB2)/sdB2, zRough = (Roughness-mR2)/sdR2) %>% 
  dplyr::select(-A, -Z, -T)
zSLP <- full_join(zSLP1, zSLP2, by = "dummy") %>% 
  dplyr::select(-Speaker.x, -Speaker.y)
 
zSLP$mzB = rowMeans(zSLP[,c('zBreathy.x', 'zBreathy.y')], na.rm=TRUE)
zSLP$mzR = rowMeans(zSLP[,c('zRough.x', 'zRough.y')], na.rm=TRUE)
glimpse(zSLP)
```

```{r}
#join the two listening results tables by matching both Speaker and T
zAVQI <-inner_join(AVQI,zSLP, by = "dummy") #%>% 
  #dplyr::select(-Speaker.x, -Speaker.y, -T, -Version)
#nrow(AVQI_RB) #192 (= 96 *2)
glimpse(zAVQI)
nrow(zAVQI)
```

```{r}
breathyRough <- lm(mzB ~ mzR, data = zAVQI)
summary(breathyRough)
```

```{r}
mzBCorr <- fitted(breathyRough, zAVQI$mzR)
zAVQI$mzBDecorr <- (zAVQI$mzB - mzBCorr)
```


```{r}
zAVQI_c <- na.omit(zAVQI)#removing rows containing NAs
nrow(zAVQI_c)
zRoughModel.tmp <- lm(mzR ~ CPPS + HNR + Jitter + Shimmer + ShdB + Slope + Tilt, zAVQI_c)
step(zRoughModel.tmp)
zRoughModel <- step(zRoughModel.tmp)
summary(zRoughModel)
```
HNR

```{r}
mzRoughModel <- lm(mzR ~ HNR + CPPS, data = zAVQI_c)
summary(mzRoughModel)
```

```{r}
zBrDecorrModel.tmp <- lm(mzBDecorr ~ CPPS + HNR + Jitter + Shimmer + ShdB + Slope + Tilt, zAVQI_c)
zBrDecorrModel <- step(zBrDecorrModel.tmp)
summary(zBrDecorrModel)
```
CPPS, HNR, ShdB

```{r}
BrDecorr <- lm(mzBDecorr ~ CPPS + HNR + ShdB, data = zAVQI_c) 
summary(BrDecorr)
```
^ShdB becomes not significant

```{r}
mzBreathyModel <- lm(mzB ~ HNR + CPPS, data = zAVQI_c)
summary(mzBreathyModel)
```
HNR+CPPS for breathiness, HNR not as significant

```{r}
mzBreathyModel2 <- lm(mzB ~ HNR + CPPS+ ShdB, data = zAVQI_c)
summary(mzBreathyModel2)
```
^HNR becomes even less significant after adding in ShdB.

```{r}
plot(mzR ~ CPPS, data = zAVQI_c)
abline(mzRoughModel)
	#see the predicted against by SLP plot and plot that
```
```{r}
plot(mzR ~ HNR, data = zAVQI_c)
abline(mzRoughModel)
```

```{r}
library(scatterplot3d)
rough3d<- scatterplot3d(zAVQI_c$HNR, zAVQI_c$CPPS, zAVQI_c$mzR, xlab = "HNR", ylab = "CPPS", zlab = "RoughZ")
rough3d$plane3d(mzRoughModel)

```

```{r}
plot(mzRoughModel)
```

```{r}
plot(mzB ~ CPPS, data = zAVQI_c)
abline(mzBreathyModel)
```

```{r}
plot(mzB ~ CPPS, data = zAVQI_c)
abline(mzBreathyModel)
```


The regression line is not showing up on the scatter plot, trying directly "plot(model)"
```{r}
plot(mzBreathyModel)
```



```{r}
breathy3d<- scatterplot3d(zAVQI_c$CPPS, zAVQI_c$HNR, zAVQI_c$mzB, xlab = "HNR", ylab = "CPPS", zlab = "BreathyZ")
breathy3d$plane3d(mzBreathyModel)
```

```{r}
breathy3dDecorr<- scatterplot3d(x = zAVQI_c$HNR, y = zAVQI_c$CPPS, z = zAVQI_c$mzBDecorr, xlab = "HNR", ylab = "CPPS", zlab = "BreathyZ")
breathy3dDecorr$plane3d(mzBreathyModel)
```

```{r}
plot(AVQI ~ CPPS, data = zAVQI)
```

```{r}
severityCPPS<-lm(AVQI ~ CPPS, data = zAVQI)
summary(severityCPPS)
```

```{r}
plot(AVQI ~ HNR, data = zAVQI)
```

```{r}
severityHNR <- lm(AVQI ~ HNR, data = zAVQI)
summary(severityHNR)
```

```{r}
breathyHNR<- lm(mzB ~ HNR, data = zAVQI)
summary(breathyHNR)
```

```{r}
decorrBrHNR <- lm(mzBDecorr ~ HNR, data = zAVQI)
summary(decorrBrHNR)
```

